Improve Docker Setup and Automate Image Release
domdomegg/aws-ses-v2-local pull request #29
Opened 2024-09-18 15:06 UTC by DAcodedBEAT

## Description

This PR refines the Docker setup and adds automation for releasing Docker images.

see: https://github.com/domdomegg/aws-ses-v2-local/issues/26

## Changes

1. `.dockerignore`:
    * Added to reduce Docker image size by excluding unnecessary files.
2. GitHub Actions Workflow:
    * New workflow to automatically build and push Docker images to GitHub Container Registry on release.
3. `Dockerfile`:
    * Switched to a multi-stage build for smaller images.
    * Uses a secure base image (distroless) and runs as a non-root user.
4. `docker-compose.example.yaml`:
    * Updated to use the GitHub Container Registry image.
5. `package.json` and `package-lock.json`:
    * Added Docker build and publish scripts.
    * Adjusted dependencies for production use.

## Why

* Optimize Docker image size and security.
* Automate Docker image builds and pushes.

## Testing

* Verified Docker build locally.

2024-09-19 14:12 UTC, DAcodedBEAT commented
@domdomegg once you are good with this, I plan on updating dependencies. (figured that was out of scope of this PR)

2024-09-20 19:07 UTC, domdomegg requested changes
Looks great, thank you. A few minor changes requested inline :)

2024-09-20 19:07 UTC, domdomegg commented on .github/workflows/docker-image-release.yml
> +  release:
Can we keep this trigger in line with the other release workflow, i.e. using tags?

2024-09-20 19:07 UTC, domdomegg commented on .github/workflows/docker-image-release.yml
> +    name: Push Docker image to multiple registries
```suggestion
    name: Push Docker image to registry
```

Appears to be just GHCR?

2024-09-20 21:31 UTC, DAcodedBEAT commented on .github/workflows/docker-image-release.yml
> +    name: Push Docker image to multiple registries
originally had this as pushing to docker hub too but I was unsure what you wanted to do here (or if you had a dockerhub account on your end), so I guess my question is what do you prefer?

2024-09-20 22:40 UTC, domdomegg commented on .github/workflows/docker-image-release.yml
> +    name: Push Docker image to multiple registries
I think I prefer just GHCR for now :)

2025-06-12 18:28 UTC, DAcodedBEAT commented
@domdomegg apologies for forgetting about this - I just pushed up the changes you requested :)

2025-06-17 17:26 UTC, domdomegg approved these changes

2025-06-17 17:26 UTC, merged

2025-06-17 17:32 UTC, domdomegg commented
Whoo - container released onto GHCR from 2.5.2: https://github.com/domdomegg/aws-ses-v2-local/pkgs/container/aws-ses-v2-local

@DAcodedBEAT can you check this works for your use case?

2025-06-18 00:39 UTC, DAcodedBEAT commented
> Whoo - container released onto GHCR from 2.5.2: https://github.com/domdomegg/aws-ses-v2-local/pkgs/container/aws-ses-v2-local
> 
> @DAcodedBEAT can you check this works for your use case?

Thanks @domdomegg ! This works, but I made a follow up so ARM machines (macOS, linux on ARM) can have native containers: https://github.com/domdomegg/aws-ses-v2-local/pull/45